# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- script: gradle install
  displayName: 'gradle install'


- script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
  displayName: 'Download the latest Unified Agent'
 
- script: 'java -jar wss-unified-agent.jar -c wss-unified-agent.config -apiKey 21ed7db17fe54dc28faad69005a946a2a41b30fc390c4b4f891c35059ad491b0 -product AzureDevOps -project AzureThird'
  displayName: 'Run Unified Agent Scan'